<?php
require_once __DIR__ . '/includes/base.php';

$error = '';
$success = '';
$step = chatspace_configured() ? 'admin' : 'database';

function setup_admin_exists(): bool {
    if (!chatspace_configured()) return false;
    try {
        $pdo = db();
        return (bool)$pdo->query("SELECT id FROM users WHERE role = 'admin' LIMIT 1")->fetchColumn();
    } catch (Throwable) {
        return false;
    }
}

function setup_requirements(): array {
    return [
        'php' => ['label' => 'PHP 8.2+', 'ok' => version_compare(PHP_VERSION, '8.2.0', '>='), 'required' => true],
        'pdo' => ['label' => 'PDO', 'ok' => extension_loaded('pdo'), 'required' => true],
        'pdo_sqlite' => ['label' => 'PDO SQLite', 'ok' => extension_loaded('pdo_sqlite'), 'required' => true],
        'pdo_mysql' => ['label' => 'PDO MySQL', 'ok' => extension_loaded('pdo_mysql'), 'required' => false],
        'fileinfo' => ['label' => 'Fileinfo uploads', 'ok' => extension_loaded('fileinfo'), 'required' => true],
        'gd' => ['label' => 'GD image handling', 'ok' => extension_loaded('gd'), 'required' => true],
        'mbstring' => ['label' => 'mbstring text handling', 'ok' => extension_loaded('mbstring'), 'required' => true],
        'openssl' => ['label' => 'OpenSSL password/session safety', 'ok' => extension_loaded('openssl'), 'required' => true],
        'zip' => ['label' => 'Zip backups/packages', 'ok' => extension_loaded('zip'), 'required' => false],
        'uploads' => ['label' => 'Writable uploads directory', 'ok' => is_writable(__DIR__ . '/assets/uploads') || is_writable(__DIR__ . '/assets'), 'required' => true],
        'includes' => ['label' => 'Writable includes directory', 'ok' => is_writable(__DIR__ . '/includes'), 'required' => true],
        'dbdir' => ['label' => 'Writable db directory', 'ok' => is_writable(__DIR__ . '/db'), 'required' => true],
    ];
}

function write_setup_config(array $cfg): void {
    $lines = ["<?php", "// Auto-generated by ChatSpace CE setup. Edit carefully.", "const CHATSPACE_DB_DRIVER = " . var_export($cfg['driver'], true) . ";"];
    if ($cfg['driver'] === 'mysql') {
        $lines[] = "const CHATSPACE_DB_HOST = " . var_export($cfg['host'], true) . ";";
        $lines[] = "const CHATSPACE_DB_PORT = " . (int)$cfg['port'] . ";";
        $lines[] = "const CHATSPACE_DB_NAME = " . var_export($cfg['name'], true) . ";";
        $lines[] = "const CHATSPACE_DB_USER = " . var_export($cfg['user'], true) . ";";
        $lines[] = "const CHATSPACE_DB_PASS = " . var_export($cfg['pass'], true) . ";";
    } else {
        $lines[] = "const CHATSPACE_SQLITE_PATH = __DIR__ . '/../db/chatspace.sqlite';";
    }
    file_put_contents(CHATSPACE_CONFIG, implode("\n", $lines) . "\n");
}

function setup_avatar_upload(): string {
    if (empty($_FILES['avatar']['tmp_name']) || !is_uploaded_file($_FILES['avatar']['tmp_name'])) {
        throw new RuntimeException('Admin avatar is required.');
    }
    $finfo = new finfo(FILEINFO_MIME_TYPE);
    $mime = $finfo->file($_FILES['avatar']['tmp_name']) ?: '';
    $allowed = ['image/jpeg' => 'jpg', 'image/png' => 'png', 'image/gif' => 'gif', 'image/webp' => 'webp'];
    if (!isset($allowed[$mime]) || (int)$_FILES['avatar']['size'] > 5 * 1024 * 1024) {
        throw new RuntimeException('Use a JPEG, PNG, GIF, or WEBP avatar under 5 MB.');
    }
    $dir = __DIR__ . '/assets/uploads/avatars';
    if (!is_dir($dir)) mkdir($dir, 0775, true);
    $file = bin2hex(random_bytes(12)) . '.' . $allowed[$mime];
    $dest = $dir . '/' . $file;
    if (!move_uploaded_file($_FILES['avatar']['tmp_name'], $dest)) {
        throw new RuntimeException('Could not save admin avatar.');
    }
    return '/assets/uploads/avatars/' . $file;
}

if (setup_admin_exists() && ($_GET['done'] ?? '') !== '1') {
    redirect_to('/login.php');
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['step'] ?? '') === 'database') {
    $driver = (string)($_POST['db_driver'] ?? 'sqlite');
    if (!in_array($driver, ['sqlite', 'mysql'], true)) {
        $error = 'Choose SQLite or MySQL/MariaDB.';
    } else {
        try {
            if ($driver === 'sqlite') {
                if (!extension_loaded('pdo_sqlite')) throw new RuntimeException('PDO SQLite is required for SQLite installs.');
                if (!is_writable(__DIR__ . '/includes') || !is_writable(__DIR__ . '/db')) throw new RuntimeException('includes/ and db/ must be writable.');
                write_setup_config(['driver' => 'sqlite']);
                require_once CHATSPACE_CONFIG;
                db();
                redirect_to('/setup.php');
            }

            if (!extension_loaded('pdo_mysql')) throw new RuntimeException('PDO MySQL is required for MySQL/MariaDB installs.');
            $host = trim((string)($_POST['db_host'] ?? '127.0.0.1'));
            $port = (int)($_POST['db_port'] ?? 3306);
            $name = preg_replace('/[^A-Za-z0-9_]/', '', trim((string)($_POST['db_name'] ?? 'chatspace_ce')));
            $dbUser = trim((string)($_POST['db_user'] ?? ''));
            $dbPass = (string)($_POST['db_pass'] ?? '');
            if ($host === '' || $name === '' || $dbUser === '') throw new RuntimeException('Database host, name, and user are required.');

            $server = new PDO("mysql:host={$host};port={$port};charset=utf8mb4", $dbUser, $dbPass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
            $server->exec("CREATE DATABASE IF NOT EXISTS `{$name}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $test = new PDO("mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4", $dbUser, $dbPass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);
            migrate($test);
            write_setup_config(['driver' => 'mysql', 'host' => $host, 'port' => $port, 'name' => $name, 'user' => $dbUser, 'pass' => $dbPass]);
            redirect_to('/setup.php');
        } catch (Throwable $e) {
            $error = $e->getMessage();
            $step = 'database';
        }
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['step'] ?? '') === 'admin') {
    $name = trim((string)($_POST['display_name'] ?? ''));
    $email = trim((string)($_POST['email'] ?? ''));
    $password = (string)($_POST['password'] ?? '');
    $confirm = (string)($_POST['confirm_password'] ?? '');
    try {
        if (!chatspace_configured()) throw new RuntimeException('Database setup is not complete.');
        if ($name === '' || !filter_var($email, FILTER_VALIDATE_EMAIL)) throw new RuntimeException('Display name and a valid email are required.');
        if (strlen($password) < 8 || $password !== $confirm) throw new RuntimeException('Use matching passwords of at least 8 characters.');
        $avatar = setup_avatar_upload();
        $pdo = db();
        $stmt = $pdo->prepare('INSERT INTO users (email, password_hash, display_name, role, avatar_path) VALUES (?,?,?,?,?)');
        $stmt->execute([$email, password_hash($password, PASSWORD_DEFAULT), $name, 'admin', $avatar]);
        $_SESSION['user_id'] = (int)$pdo->lastInsertId();
        redirect_to('/setup.php?done=1');
    } catch (Throwable $e) {
        $error = $e->getMessage();
        $step = 'admin';
    }
}

if (($_GET['done'] ?? '') === '1') $step = 'done';
$requirements = setup_requirements();
$requiredMissing = array_filter($requirements, fn($r) => $r['required'] && !$r['ok']);
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Setup - ChatSpace CE</title>
  <link rel="stylesheet" href="<?= e(app_url('/assets/css/styles.css')) ?>">
</head>
<body data-app-base="<?= e(app_base_path()) ?>">
<main class="setup-shell">
  <section class="setup-card">
    <div class="app-title setup-brand">
      <img src="<?= e(app_url('/assets/images/chatspace-ce-logo.png')) ?>" alt="">
      <div>
        <div class="app-name">ChatSpace</div>
        <div class="app-edition">Community Edition</div>
      </div>
    </div>
    <div class="setup-steps">
      <span class="setup-step <?= $step === 'database' ? 'active' : 'done' ?>">Database</span>
      <span class="setup-step-sep">→</span>
      <span class="setup-step <?= $step === 'admin' ? 'active' : (in_array($step, ['done'], true) ? 'done' : '') ?>">Admin User</span>
      <span class="setup-step-sep">→</span>
      <span class="setup-step <?= $step === 'done' ? 'active' : '' ?>">Finalize</span>
    </div>

    <?php if ($error): ?><div class="setup-alert setup-alert-error"><?= e($error) ?></div><?php endif; ?>
    <?php if ($success): ?><div class="setup-alert setup-alert-ok"><?= e($success) ?></div><?php endif; ?>

    <?php if ($step === 'database'): ?>
      <h1>Database Setup</h1>
      <p class="subtitle">Choose the database engine for this ChatSpace installation.</p>
      <div class="setup-preflight">
        <?php foreach ($requirements as $req): ?>
          <div class="setup-check <?= $req['ok'] ? 'ok' : ($req['required'] ? 'bad' : 'warn') ?>">
            <span><?= $req['ok'] ? '✓' : '!' ?></span>
            <strong><?= e($req['label']) ?></strong>
            <em><?= $req['required'] ? 'Required' : 'Optional' ?></em>
          </div>
        <?php endforeach; ?>
      </div>
      <form method="post" class="setup-form" novalidate>
        <input type="hidden" name="step" value="database">
        <div class="setup-choice-grid">
          <label class="setup-choice">
            <input class="setup-db-radio" type="radio" name="db_driver" value="sqlite" checked>
            <span class="setup-choice-card">
              <strong>SQLite</strong>
              <span>Single-file database, easiest to move, backup, and test locally.</span>
              <em>Recommended for Community Edition</em>
            </span>
          </label>
          <label class="setup-choice">
            <input class="setup-db-radio" type="radio" name="db_driver" value="mysql">
            <span class="setup-choice-card">
              <strong>MySQL / MariaDB</strong>
              <span>Use an existing database server or a fakeSQL compatibility host.</span>
              <em>For hosted database environments</em>
            </span>
          </label>
        </div>
        <div class="mysql-fields" id="setup-mysql-fields" hidden>
          <div class="form-row">
            <label>Database host<input name="db_host" value="<?= e($_POST['db_host'] ?? '127.0.0.1') ?>"></label>
            <label>Port<input name="db_port" type="number" value="<?= e($_POST['db_port'] ?? '3306') ?>"></label>
          </div>
          <label>Database name<input name="db_name" value="<?= e($_POST['db_name'] ?? 'chatspace_ce') ?>"></label>
          <div class="form-row">
            <label>Username<input name="db_user" value="<?= e($_POST['db_user'] ?? 'root') ?>" autocomplete="username"></label>
            <label>Password<input name="db_pass" type="password" autocomplete="current-password"></label>
          </div>
        </div>
        <button class="btn btn-primary setup-submit" type="submit" <?= $requiredMissing ? 'disabled' : '' ?>>Continue</button>
      </form>
    <?php elseif ($step === 'admin'): ?>
      <h1>Create Admin User</h1>
      <p class="subtitle">This account controls the community, rooms, users, and moderation tools.</p>
      <form method="post" class="setup-form" enctype="multipart/form-data" novalidate>
        <input type="hidden" name="step" value="admin">
        <label>Display name<input name="display_name" required></label>
        <label>Avatar image
          <span class="file-picker">
            <input id="setup-avatar" type="file" name="avatar" accept="image/jpeg,image/png,image/gif,image/webp" required>
            <span class="file-picker-btn">Choose Avatar</span>
            <span class="file-picker-name" id="setup-avatar-name">No file selected</span>
          </span>
        </label>
        <label>Email<input name="email" type="email" required autocomplete="email"></label>
        <div class="form-row">
          <label>Password<input name="password" type="password" minlength="8" required autocomplete="new-password"></label>
          <label>Confirm password<input name="confirm_password" type="password" minlength="8" required autocomplete="new-password"></label>
        </div>
        <button class="btn btn-primary setup-submit" type="submit">Create Admin</button>
      </form>
    <?php else: ?>
      <h1>Setup Complete</h1>
      <p class="subtitle">ChatSpace Community Edition is ready.</p>
      <a class="btn btn-primary setup-submit" href="<?= e(app_url('/lobby.php')) ?>">Enter Lobby</a>
    <?php endif; ?>
  </section>
</main>
<script src="<?= e(app_url('/assets/js/setup.js')) ?>"></script>
</body>
</html>
