<?php
require_once __DIR__ . '/includes/base.php';
require_once __DIR__ . '/includes/database_backups.php';

$error = '';
$success = '';
$step = chatspace_configured() ? 'admin' : 'database';

function setup_direct_pdo(): PDO {
    if (db_driver() === 'mysql') {
        $host = defined('CHATSPACE_DB_HOST') ? CHATSPACE_DB_HOST : '127.0.0.1';
        $port = (int)(defined('CHATSPACE_DB_PORT') ? CHATSPACE_DB_PORT : 3306);
        $name = defined('CHATSPACE_DB_NAME') ? CHATSPACE_DB_NAME : 'chatspace_ce';
        $user = defined('CHATSPACE_DB_USER') ? CHATSPACE_DB_USER : 'root';
        $pass = defined('CHATSPACE_DB_PASS') ? CHATSPACE_DB_PASS : '';
        return new PDO("mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4", $user, $pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);
    }
    $pdo = new PDO('sqlite:' . sqlite_path());
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    return $pdo;
}

function setup_admin_exists(bool $sharedConnection = true): bool {
    if (!chatspace_configured()) return false;
    try {
        $pdo = $sharedConnection ? db() : setup_direct_pdo();
        $exists = (bool)$pdo->query("SELECT id FROM users WHERE role = 'admin' LIMIT 1")->fetchColumn();
        if (!$sharedConnection) $pdo = null;
        return $exists;
    } catch (Throwable) {
        return false;
    }
}

function setup_requirements(): array {
    return [
        'php' => ['label' => 'PHP 8.2+', 'ok' => version_compare(PHP_VERSION, '8.2.0', '>='), 'required' => true],
        'pdo' => ['label' => 'PDO', 'ok' => extension_loaded('pdo'), 'required' => true],
        'pdo_sqlite' => ['label' => 'PDO SQLite', 'ok' => extension_loaded('pdo_sqlite'), 'required' => true],
        'pdo_mysql' => ['label' => 'PDO MySQL', 'ok' => extension_loaded('pdo_mysql'), 'required' => false],
        'fileinfo' => ['label' => 'Fileinfo uploads', 'ok' => extension_loaded('fileinfo'), 'required' => true],
        'gd' => ['label' => 'GD image handling', 'ok' => extension_loaded('gd'), 'required' => true],
        'mbstring' => ['label' => 'mbstring text handling', 'ok' => extension_loaded('mbstring'), 'required' => true],
        'openssl' => ['label' => 'OpenSSL password/session safety', 'ok' => extension_loaded('openssl'), 'required' => true],
        'curl' => ['label' => 'cURL secure remote imports', 'ok' => extension_loaded('curl'), 'required' => true],
        'zip' => ['label' => 'Zip backups/packages', 'ok' => extension_loaded('zip'), 'required' => false],
        'uploads' => ['label' => 'Writable uploads directory', 'ok' => is_writable(__DIR__ . '/assets/uploads') || is_writable(__DIR__ . '/assets'), 'required' => true],
        'includes' => ['label' => 'Writable includes directory', 'ok' => is_writable(__DIR__ . '/includes'), 'required' => true],
        'dbdir' => ['label' => 'Writable db directory', 'ok' => is_writable(__DIR__ . '/db'), 'required' => true],
    ];
}

function setup_sqlite_path(): string {
    $dir = __DIR__ . '/db';
    $defaultPath = $dir . '/chatspace.sqlite';
    if (!is_file($defaultPath)) {
        throw new RuntimeException('The bundled SQLite database file is missing.');
    }
    for ($i = 0; $i < 8; $i++) {
        $file = 'chatspace-' . uuid_v4() . '.sqlite';
        $path = $dir . '/' . $file;
        if (file_exists($path)) continue;
        if (!copy($defaultPath, $path)) {
            throw new RuntimeException('Could not copy the bundled SQLite database.');
        }
        return $path;
    }
    throw new RuntimeException('Could not generate a unique SQLite database path.');
}

function write_setup_config(array $cfg): void {
    $lines = ["<?php", "// Auto-generated by ChatSpace CE setup. Edit carefully.", "const CHATSPACE_DB_DRIVER = " . var_export($cfg['driver'], true) . ";"];
    if ($cfg['driver'] === 'mysql') {
        $lines[] = "const CHATSPACE_DB_HOST = " . var_export($cfg['host'], true) . ";";
        $lines[] = "const CHATSPACE_DB_PORT = " . (int)$cfg['port'] . ";";
        $lines[] = "const CHATSPACE_DB_NAME = " . var_export($cfg['name'], true) . ";";
        $lines[] = "const CHATSPACE_DB_USER = " . var_export($cfg['user'], true) . ";";
        $lines[] = "const CHATSPACE_DB_PASS = " . var_export($cfg['pass'], true) . ";";
    } else {
        $sqlitePath = realpath($cfg['sqlite_path'] ?? '') ?: (string)($cfg['sqlite_path'] ?? '');
        $dbDir = realpath(__DIR__ . '/db') ?: (__DIR__ . '/db');
        if ($sqlitePath === '' || !str_starts_with($sqlitePath, $dbDir . DIRECTORY_SEPARATOR)) {
            throw new RuntimeException('SQLite database path must stay inside the db directory.');
        }
        $lines[] = "const CHATSPACE_SQLITE_PATH = __DIR__ . '/../db/" . basename($sqlitePath) . "';";
    }
    file_put_contents(CHATSPACE_CONFIG, implode("\n", $lines) . "\n");
}

function setup_avatar_upload(): string {
    security_authorize_outside_content_or_json(chatspace_configured() ? db() : null, null, 'setup_avatar', ['setup_allowed' => !setup_admin_exists(), 'source' => 'setup']);
    if (empty($_FILES['avatar']['tmp_name']) || !is_uploaded_file($_FILES['avatar']['tmp_name'])) {
        throw new RuntimeException('Admin avatar is required.');
    }
    $finfo = new finfo(FILEINFO_MIME_TYPE);
    $mime = $finfo->file($_FILES['avatar']['tmp_name']) ?: '';
    $allowed = ['image/gif' => 'gif', 'image/webp' => 'webp'];
    $dims = @getimagesize($_FILES['avatar']['tmp_name']);
    if (!isset($allowed[$mime]) || !security_valid_image_file((string)$_FILES['avatar']['tmp_name'], $mime) || (int)$_FILES['avatar']['size'] > 5 * 1024 * 1024 || !$dims || $dims[0] < 42 || $dims[1] < 42 || $dims[0] > 250 || $dims[1] > 250) {
        throw new RuntimeException('Use an optimized GIF or WEBP avatar under 5 MB and between 42x42 and 250x250.');
    }
    $dir = __DIR__ . '/assets/uploads/avatars';
    if (!is_dir($dir)) mkdir($dir, 0775, true);
    $file = bin2hex(random_bytes(12)) . '.' . $allowed[$mime];
    $dest = $dir . '/' . $file;
    if (!move_uploaded_file($_FILES['avatar']['tmp_name'], $dest)) {
        throw new RuntimeException('Could not save admin avatar.');
    }
    $public = '/assets/uploads/avatars/' . $file;
    security_assert_storage_destination('setup_avatar', $public);
    return $public;
}

function setup_brand_logo_upload(): string {
    if (empty($_FILES['community_logo']['tmp_name']) || !is_uploaded_file($_FILES['community_logo']['tmp_name'])) {
        return '';
    }
    security_authorize_outside_content_or_json(chatspace_configured() ? db() : null, null, 'setup_branding', ['setup_allowed' => !setup_admin_exists(), 'source' => 'setup']);
    $finfo = new finfo(FILEINFO_MIME_TYPE);
    $mime = $finfo->file($_FILES['community_logo']['tmp_name']) ?: '';
    $allowed = [
        'image/png' => 'png',
        'image/jpeg' => 'jpg',
        'image/gif' => 'gif',
        'image/webp' => 'webp',
    ];
    $dims = @getimagesize($_FILES['community_logo']['tmp_name']);
    if (!isset($allowed[$mime]) || !security_valid_image_file((string)$_FILES['community_logo']['tmp_name'], $mime) || (int)$_FILES['community_logo']['size'] > 5 * 1024 * 1024 || !$dims || $dims[0] < 42 || $dims[1] < 42 || $dims[0] > 2000 || $dims[1] > 2000) {
        throw new RuntimeException('Use a PNG, JPG, GIF, or WEBP logo under 5 MB and between 42x42 and 2000x2000.');
    }
    $dir = __DIR__ . '/assets/uploads/branding';
    if (!is_dir($dir)) mkdir($dir, 0775, true);
    $file = bin2hex(random_bytes(12)) . '.' . $allowed[$mime];
    $dest = $dir . '/' . $file;
    if (!move_uploaded_file($_FILES['community_logo']['tmp_name'], $dest)) {
        throw new RuntimeException('Could not save community logo.');
    }
    $public = '/assets/uploads/branding/' . $file;
    security_assert_storage_destination('setup_branding', $public);
    return $public;
}

function setup_response(array $payload, int $status = 200): never {
    json_out($payload, $status);
}

function setup_restore_backup_upload(): array {
    if (!chatspace_configured()) throw new RuntimeException('Database setup is not complete.');
    if (setup_admin_exists(false)) throw new RuntimeException('Setup restore is only available before the first admin account exists.');
    if (empty($_FILES['database']['tmp_name']) || !is_uploaded_file($_FILES['database']['tmp_name'])) {
        throw new RuntimeException('Choose a backup file to import.');
    }
    security_authorize_outside_content_or_json(db(), null, 'setup_database_import', ['setup_allowed' => !setup_admin_exists(false), 'source' => 'setup_restore']);
    $tmp = $_FILES['database']['tmp_name'];
    $actualBytes = filesize((string)$tmp);
    if ($actualBytes === false || $actualBytes < 1 || $actualBytes > app_setting_bytes(db(), 'database_import_max_size_mb', 512)) {
        throw new RuntimeException('Import file exceeds the configured backup size limit.');
    }
    $decoded = json_decode((string)file_get_contents($tmp), true);
    if (is_array($decoded) && ($decoded['format'] ?? '') === 'chatspace-ce-portable-bundle') {
        $result = backup_import_core_bundle(db(), $decoded, 0);
    } else {
        $result = backup_restore_sqlite_upload($tmp, true, 0);
    }
    if (!setup_admin_exists()) {
        throw new RuntimeException('Backup restored, but it did not include an admin account. Import a backup with an admin user or create a new admin user.');
    }
    unset($_SESSION['user_id'], $_SESSION['session_locked']);
    return $result;
}

$isSetupRestorePost = $_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['step'] ?? '') === 'restore';
if (!$isSetupRestorePost && setup_admin_exists() && ($_GET['done'] ?? '') !== '1') {
    redirect_to('/login.php');
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['step'] ?? '') === 'database') {
    $driver = (string)($_POST['db_driver'] ?? 'sqlite');
    if (!in_array($driver, ['sqlite', 'mysql'], true)) {
        $error = 'Choose SQLite or MySQL/MariaDB.';
    } else {
        try {
            if ($driver === 'sqlite') {
                if (!extension_loaded('pdo_sqlite')) throw new RuntimeException('PDO SQLite is required for SQLite installs.');
                if (!is_writable(__DIR__ . '/includes') || !is_writable(__DIR__ . '/db')) throw new RuntimeException('includes/ and db/ must be writable.');
                $sqlitePath = setup_sqlite_path();
                write_setup_config(['driver' => 'sqlite', 'sqlite_path' => $sqlitePath]);
                require_once CHATSPACE_CONFIG;
                migrate(db_migration_connection());
                redirect_to('/setup.php');
            }

            if (!extension_loaded('pdo_mysql')) throw new RuntimeException('PDO MySQL is required for MySQL/MariaDB installs.');
            $host = trim((string)($_POST['db_host'] ?? '127.0.0.1'));
            $port = (int)($_POST['db_port'] ?? 3306);
            $name = preg_replace('/[^A-Za-z0-9_]/', '', trim((string)($_POST['db_name'] ?? 'chatspace_ce')));
            $dbUser = trim((string)($_POST['db_user'] ?? ''));
            $dbPass = (string)($_POST['db_pass'] ?? '');
            if ($host === '' || $name === '' || $dbUser === '') throw new RuntimeException('Database host, name, and user are required.');

            $server = new PDO("mysql:host={$host};port={$port};charset=utf8mb4", $dbUser, $dbPass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
            $server->exec("CREATE DATABASE IF NOT EXISTS `{$name}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $test = new PDO("mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4", $dbUser, $dbPass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);
            migrate($test);
            write_setup_config(['driver' => 'mysql', 'host' => $host, 'port' => $port, 'name' => $name, 'user' => $dbUser, 'pass' => $dbPass]);
            redirect_to('/setup.php');
        } catch (Throwable $e) {
            $error = $e->getMessage();
            $step = 'database';
        }
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['step'] ?? '') === 'admin') {
    $name = trim((string)($_POST['display_name'] ?? ''));
    $email = trim((string)($_POST['email'] ?? ''));
    $password = (string)($_POST['password'] ?? '');
    $confirm = (string)($_POST['confirm_password'] ?? '');
    try {
        if (!chatspace_configured()) throw new RuntimeException('Database setup is not complete.');
        if ($name === '' || !filter_var($email, FILTER_VALIDATE_EMAIL)) throw new RuntimeException('Display name and a valid email are required.');
        if (strlen($password) < 8 || $password !== $confirm) throw new RuntimeException('Use matching passwords of at least 8 characters.');
        $registryValues = json_decode((string)($_POST['settings_registry_values'] ?? ''), true);
        if (!is_array($registryValues)) {
            $registryValues = [];
            foreach (settings_registry_snapshot(db(), 'setup')['visibleEntries'] as $entry) {
                if (!in_array($entry['type'], ['asset', 'fixed', 'secret'], true)) $registryValues[$entry['id']] = $entry['currentValue'];
            }
        }
        $communityName = trim((string)($registryValues['community_name'] ?? ''));
        if ((function_exists('mb_strlen') ? mb_strlen($communityName, 'UTF-8') : strlen($communityName)) > 80) {
            throw new RuntimeException('Community name must be 80 characters or less.');
        }
        $communityLogo = setup_brand_logo_upload();
        $avatar = setup_avatar_upload();
        $pdo = db();
        if (db_uses_mysql_syntax($pdo)) $pdo->beginTransaction();
        else $pdo->exec('BEGIN IMMEDIATE TRANSACTION');
        try {
            $stmt = $pdo->prepare('INSERT INTO users (email, password_hash, display_name, role, avatar_path) VALUES (?,?,?,?,?)');
            $stmt->execute([$email, password_hash($password, PASSWORD_DEFAULT), $name, 'admin', $avatar]);
            $adminUserId = (int)$pdo->lastInsertId();
            $registryValues['community_name'] = $communityName;
            if ($communityLogo !== '') $registryValues['community_logo_path'] = $communityLogo;
            $registryResult = settings_registry_update(
                $pdo,
                ['operation' => 'set_many', 'values' => $registryValues, 'confirmed' => true],
                $_POST['settings_registry_revision'] ?? null,
                $adminUserId,
                'setup'
            );
            if (empty($registryResult['ok'])) throw new RuntimeException((string)($registryResult['error'] ?? 'Setup settings could not be saved.'));
            $pdo->commit();
        } catch (Throwable $transactionError) {
            if ($pdo->inTransaction()) $pdo->rollBack();
            throw $transactionError;
        }
        authenticate_user($adminUserId);
        redirect_to('/setup.php?done=1');
    } catch (Throwable $e) {
        $error = $e->getMessage();
        $step = 'admin';
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['step'] ?? '') === 'restore') {
    try {
        setup_restore_backup_upload();
        setup_response(['ok' => true, 'redirect' => app_url('/setup.php?done=1&restored=1')]);
    } catch (Throwable $e) {
        $accept = strtolower((string)($_SERVER['HTTP_ACCEPT'] ?? ''));
        if (str_contains($accept, 'application/json') || (string)($_SERVER['HTTP_X_REQUESTED_WITH'] ?? '') === 'XMLHttpRequest') {
            setup_response(['error' => $e->getMessage()], 400);
        }
        $error = $e->getMessage();
        $step = 'admin';
    }
}

if (($_GET['done'] ?? '') === '1') $step = 'done';
$restoredSetup = ($_GET['restored'] ?? '') === '1';
$requirements = setup_requirements();
$requiredMissing = array_filter($requirements, fn($r) => $r['required'] && !$r['ok']);
$setupSettingsRegistry = $step === 'admin' && chatspace_configured() ? settings_registry_snapshot(db(), 'setup') : null;
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Setup - ChatSpace CE</title>
  <link rel="stylesheet" href="<?= e(app_url('/assets/css/styles.css')) ?>">
</head>
<body data-app-base="<?= e(app_base_path()) ?>" data-csrf="<?= e(csrf_token()) ?>">
<main class="setup-shell">
  <section class="setup-card">
    <div class="app-title setup-brand setup-brand-full">
      <img src="<?= e(app_url('/assets/images/logos/chatspace-ce-full-logo.png')) ?>" alt="ChatSpace Community Edition">
    </div>
    <div class="setup-steps">
      <span class="setup-step <?= $step === 'database' ? 'active' : 'done' ?>">Database</span>
      <span class="setup-step-sep">→</span>
      <span class="setup-step <?= $step === 'admin' ? 'active' : (in_array($step, ['done'], true) ? 'done' : '') ?>">Admin User</span>
      <span class="setup-step-sep">→</span>
      <span class="setup-step <?= $step === 'done' ? 'active' : '' ?>">Finalize</span>
    </div>

    <?php if ($error): ?><div class="setup-alert setup-alert-error"><?= e($error) ?></div><?php endif; ?>
    <?php if ($success): ?><div class="setup-alert setup-alert-ok"><?= e($success) ?></div><?php endif; ?>

    <?php if ($step === 'database'): ?>
      <h1>Database Setup</h1>
      <p class="subtitle">Choose the database engine for this ChatSpace installation.</p>
      <div class="setup-preflight">
        <?php foreach ($requirements as $req): ?>
          <div class="setup-check <?= $req['ok'] ? 'ok' : ($req['required'] ? 'bad' : 'warn') ?>">
            <span><?= $req['ok'] ? '✓' : '!' ?></span>
            <strong><?= e($req['label']) ?></strong>
            <em><?= $req['required'] ? 'Required' : 'Optional' ?></em>
          </div>
        <?php endforeach; ?>
      </div>
      <form method="post" class="setup-form" novalidate>
        <?= csrf_input() ?>
        <input type="hidden" name="step" value="database">
        <div class="setup-choice-grid">
          <label class="setup-choice">
            <input class="setup-db-radio" type="radio" name="db_driver" value="sqlite" checked>
            <span class="setup-choice-card">
              <strong>SQLite</strong>
              <span>Single-file database, easiest to move, backup, and test locally.</span>
              <em>Recommended for Community Edition</em>
            </span>
          </label>
          <label class="setup-choice">
            <input class="setup-db-radio" type="radio" name="db_driver" value="mysql">
            <span class="setup-choice-card">
              <strong>MySQL / MariaDB</strong>
              <span>Use an existing database server or a fakeSQL compatibility host.</span>
              <em>For hosted database environments</em>
            </span>
          </label>
        </div>
        <div class="mysql-fields" id="setup-mysql-fields" hidden>
          <div class="form-row">
            <label>Database host<input name="db_host" value="<?= e($_POST['db_host'] ?? '127.0.0.1') ?>"></label>
            <label>Port<input name="db_port" type="number" value="<?= e($_POST['db_port'] ?? '3306') ?>"></label>
          </div>
          <label>Database name<input name="db_name" value="<?= e($_POST['db_name'] ?? 'chatspace_ce') ?>"></label>
          <div class="form-row">
            <label>Username<input name="db_user" value="<?= e($_POST['db_user'] ?? 'root') ?>" autocomplete="username"></label>
            <label>Password<input name="db_pass" type="password" autocomplete="current-password"></label>
          </div>
        </div>
        <button class="btn btn-primary setup-submit" type="submit" <?= $requiredMissing ? 'disabled' : '' ?>>Continue</button>
      </form>
    <?php elseif ($step === 'admin'): ?>
      <h1>Admin Account</h1>
      <p class="subtitle">Create the first admin user, or import an existing ChatSpace backup to restore users, rooms, settings, and files now.</p>
      <div class="setup-admin-mode">
        <button class="setup-mode-tab active" type="button" data-setup-mode="create">Create Admin User</button>
        <span>or</span>
        <button class="setup-mode-tab" type="button" data-setup-mode="restore">Import Backup</button>
      </div>
      <section class="setup-mode-panel active" id="setup-mode-create">
        <form method="post" class="setup-form" enctype="multipart/form-data" novalidate>
          <?= csrf_input() ?>
          <input type="hidden" name="step" value="admin">
          <label>Display name<input name="display_name" required></label>
          <label>Avatar image
            <span class="file-picker">
              <input id="setup-avatar" type="file" name="avatar" accept="image/jpeg,image/png,image/gif,image/webp" required>
              <span class="file-picker-btn">Choose Avatar</span>
              <span class="file-picker-name" id="setup-avatar-name">No file selected</span>
            </span>
          </label>
          <label>Email<input name="email" type="email" required autocomplete="email"></label>
          <div class="form-row">
            <label>Password<input name="password" type="password" minlength="8" required autocomplete="new-password"></label>
            <label>Confirm password<input name="confirm_password" type="password" minlength="8" required autocomplete="new-password"></label>
          </div>
          <input id="setup-settings-registry-values" type="hidden" name="settings_registry_values" value="">
          <input type="hidden" name="settings_registry_revision" value="<?= e((string)($setupSettingsRegistry['revision'] ?? 1)) ?>">
          <script id="setup-settings-registry-data" type="application/json"><?= json_encode($setupSettingsRegistry, JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?></script>
          <div class="setup-branding-fields settings-registry-setup">
            <div class="settings-registry-heading">
              <div><h2>Installation Settings</h2><p class="minor">Setup and Admin use the same setting IDs, categories, defaults, validation, and authoritative owners.</p></div>
              <div class="settings-registry-state" id="setup-settings-compatibility-state" aria-live="polite">Framework default</div>
            </div>
            <div id="setup-settings-unlock"></div>
            <div class="settings-registry-toolbar" role="search">
              <label>Search settings<input id="setup-settings-search" type="search" autocomplete="off" placeholder="Label, help, category, alias, or setting ID"></label>
              <label>Filter<select id="setup-settings-filter"><option value="all">All</option><option value="enabled">Enabled</option><option value="disabled">Disabled</option><option value="changed">Changed from default</option><option value="original">Original-author compatibility relevant</option></select></label>
            </div>
            <div class="shared-form-actions">
              <button class="btn" id="setup-settings-original" type="button">Use Original-compatible Values</button>
              <button class="btn" id="setup-settings-framework" type="button">Use Framework Defaults</button>
              <button class="btn btn-danger" id="setup-settings-reset-optional" type="button">Reset All Optional Settings</button>
            </div>
            <div id="setup-settings-registry" class="settings-registry"></div>
          </div>
          <button class="btn btn-primary setup-submit" type="submit">Create Admin User</button>
        </form>
      </section>
      <section class="setup-mode-panel" id="setup-mode-restore">
        <form method="post" class="setup-form setup-restore-form" id="setup-restore-form" enctype="multipart/form-data" novalidate>
          <?= csrf_input() ?>
          <input type="hidden" name="step" value="restore">
          <div class="setup-import-note">
            Import a full SQLite backup or a portable JSON bundle. Portable imports apply whatever sections are present and include bundled files such as avatars, room media, gestures, and link icons.
          </div>
          <label>Backup file
            <span class="file-picker">
              <input id="setup-backup-file" name="database" type="file" accept=".sqlite,.db,.json,application/json,application/vnd.sqlite3,application/octet-stream" required>
              <span class="file-picker-btn">Choose Backup</span>
              <span class="file-picker-name" id="setup-backup-name">No file selected</span>
            </span>
          </label>
          <span class="upload-progress" id="setup-backup-progress" aria-live="polite">
            <span class="upload-progress-track"><span class="upload-progress-bar"></span></span>
            <span class="upload-progress-meta"><span class="upload-progress-msg">Waiting...</span><span class="upload-progress-pct">0%</span></span>
          </span>
          <button class="btn btn-danger setup-submit" type="submit">Import Backup</button>
        </form>
      </section>
    <?php else: ?>
      <h1>Setup Complete</h1>
      <p class="subtitle"><?= $restoredSetup ? 'Backup restored. Sign in with one of the restored accounts to continue.' : 'ChatSpace Community Edition is ready.' ?></p>
      <a class="btn btn-primary setup-submit" href="<?= e(app_url($restoredSetup ? '/login.php' : '/lobby.php')) ?>"><?= $restoredSetup ? 'Go to Login' : 'Enter Lobby' ?></a>
    <?php endif; ?>
  </section>
</main>
<script src="<?= e(app_url('/assets/js/avatar-processing.js')) ?>"></script>
<script src="<?= e(app_url('/assets/js/settings-registry.js')) ?>"></script>
<script src="<?= e(app_url('/assets/js/setup.js')) ?>"></script>
</body>
</html>
