import assert from 'node:assert/strict';import fs from 'node:fs';
import {createPoolBotController} from '../games/eight-ball/bot-controller.js';
let clock=0,next=0;const timers=new Map();globalThis.setTimeout=(fn,ms)=>{const id=++next;timers.set(id,{fn,at:clock+ms});return id;};globalThis.clearTimeout=id=>timers.delete(id);Object.defineProperty(globalThis,'performance',{value:{now:()=>clock}});
async function advance(ms){const end=clock+ms;while(true){const a=[...timers.entries()].filter(([,t])=>t.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!a)break;clock=a[1].at;timers.delete(a[0]);await a[1].fn();}clock=end;}
let workers=[];class Worker{constructor(){workers.push(this);}postMessage(p){this.task=p.task;}terminate(){this.terminated=true;}}
const engine='corechat-pool-search-1';let view={enabled:true,key:'a',animating:false,task:{engine,positionKey:'a',presentationDelayMs:2000,waitForMotionMs:1000}},submitted=[],retry,status=[],ok=true;
const c=createPoolBotController({WorkerClass:Worker,snapshot:()=>view,submit:async p=>{submitted.push(p);return ok;},showStatus:(m,r)=>{status.push(m);retry=r;}});
const ready=()=>workers.at(-1).onmessage({data:{type:'result',engine,action:'shot',payload:{angle:0,power:34}}});
const checks=[];const ck=(v,m)=>{assert(v,m);checks.push(m);};
c.sync();c.sync();ck(workers.length===1,'Repeated sync starts one worker');ready();await advance(2999);ck(!submitted.length,'Waits for motion deadline plus presentation pause');view.animating=true;await advance(1000);ck(!submitted.length,'Actual unfinished animation prevents submitting');view.animating=false;await advance(900);ck(submitted.length===1,'Submits once after animation and settled gap');c.sync();await advance(5000);ck(submitted.length===1,'Same position cannot submit twice');
view={...view,key:'b',task:{...view.task,positionKey:'b',waitForMotionMs:0}};c.sync();const stale=workers.at(-1);view={...view,key:'c',task:{...view.task,positionKey:'c'}};c.sync();stale.onmessage({data:{type:'result',engine,action:'shot',payload:{}}});ck(stale.terminated,'Stale search terminated');ready();view.enabled=false;c.sync();await advance(4000);ck(submitted.length===1,'Hidden/disabled game cancels submission');
view.enabled=true;view.key='d';view.task.positionKey='d';c.sync();ok=false;ready();await advance(3000);ck(typeof retry==='function','Save failure offers Retry bot');const n=submitted.length;c.sync();await advance(3000);ck(submitted.length===n,'Failure cannot auto-spam retries');ok=true;retry();ready();await advance(3000);ck(submitted.length===n+1,'Explicit retry recovers');
view.key='e';view.task={...view.task,positionKey:'e',pendingShot:{angle:.2,power:48}};const wc=workers.length;c.sync();await advance(3000);ck(workers.length===wc&&submitted.at(-1).payload.angle===.2,'Saved plan resumes without repeating search');
view.key='f';view.task={...view.task,positionKey:'f',pendingShot:null,difficulty:'normal'};c.sync();await advance(14000);ck(typeof retry==='function'&&status.at(-1).includes('too long'),'Normal worker timeout offers retry');
view.key='g';view.task={...view.task,positionKey:'g',difficulty:'expert'};c.sync();const long=workers.at(-1);await advance(30000);ck(!long.terminated&&!retry,'Expert can think for the full thirty seconds');const prior=submitted.length;ready();await advance(701);ck(submitted.length===prior+1,'Expert result at thirty seconds is delivered');
view.key='h';view.task={...view.task,positionKey:'h'};c.sync();await advance(34999);ck(!workers.at(-1).terminated&&!retry,'Expert watchdog leaves time for worker startup and delivery');await advance(1);ck(typeof retry==='function'&&workers.at(-1).terminated,'Hung Expert terminates and offers Retry');
view.key='i';view.task={...view.task,positionKey:'i'};c.sync();const cancelled=workers.at(-1);await advance(20000);view.enabled=false;c.sync();const count=submitted.length;cancelled.onmessage({data:{type:'result',engine,action:'shot',payload:{angle:0,power:34}}});await advance(40000);ck(cancelled.terminated&&submitted.length===count,'Long Expert search cancels without stale delivery');c.stop();ck(timers.size===0,'Controller cleans all timers');
console.log(JSON.stringify({status:'PASS',checks:checks.length}));
