(function () {
  'use strict';
  const make=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
  const art=(t,h=false)=>window.DominosArtwork(...t.split('-').map(Number),h);
  let root,stage,table,ctx,lastKey='',previous=null,selected=null,animationUntil=0,epoch=0,size=100,ro,pendingDraw=false;
  const soundBase=new URL('../../assets/audio/dominos/',document.currentScript.src);
  const audio=[1,2,3].map(i=>new Audio(new URL(`placement-${i}.wav`,soundBase)));
  const shuffle=new Audio(new URL('shuffle.mp3',soundBase));let lastSound=-1;
  function stopSound(){for(const a of [...audio,shuffle]){a.pause();a.currentTime=0;}}
  function sound(deal=false){if(ctx.options?.effectsEnabled===false)return;stopSound();let a=shuffle;if(!deal){const choices=[0,1,2].filter(i=>i!==lastSound);lastSound=choices[Math.floor(Math.random()*choices.length)];a=audio[lastSound];}a.volume=Math.min(1,Math.max(0,Number(ctx.options?.masterVolume??100)/100))*.6;void a.play().catch(()=>{});if(deal){const token=epoch;setTimeout(()=>{if(token===epoch)shuffle.pause();},1400);}}
  function fit(){if(!table)return;table.style.width=size+'%';const scale=table.clientWidth/1100;stage.style.transform=`scale(${scale})`;table.style.height=640*scale+'px';root.querySelector('.dm-size-value').textContent=size+'%';}
  function stepper(button,delta){let delay,repeat;const stop=()=>{clearTimeout(delay);clearInterval(repeat);};const step=()=>{size=Math.max(50,Math.min(200,size+delta));fit();};button.onclick=step;button.onpointerdown=e=>{if(e.button!==0)return;button.setPointerCapture(e.pointerId);delay=setTimeout(()=>{step();repeat=setInterval(step,130);},400);};button.onpointerup=button.onpointercancel=button.onlostpointercapture=stop;window.addEventListener('blur',stop);}
  function setup(){root=make('section','dm-app');const tools=make('div','dm-tools');tools.append(make('span','','Board size'));const minus=make('button','','−'),plus=make('button','','+');minus.setAttribute('aria-label','Smaller board');plus.setAttribute('aria-label','Larger board');tools.append(minus,make('output','dm-size-value','100%'),plus);stepper(minus,-5);stepper(plus,5);root.append(tools);const frame=make('div','dm-frame');table=make('div','dm-table');stage=make('div','dm-stage');table.append(stage);frame.append(table);root.append(frame);ro=new ResizeObserver(fit);ro.observe(root);}
  function tile(t,cls,h=false){const n=make('div',cls);n.innerHTML=art(t,h);n.dataset.tile=t;return n;}
  const coords=s=>window.DominosLayout(s);
  function position(n,q){Object.assign(n.style,{left:(q.x-q.w/2)+'px',top:(q.y-q.h/2)+'px',width:q.w+'px',height:q.h+'px'});}
  function actions(s){const host=make('div','dm-actions');for(const a of s.legalActions||[]){if(['play','draw'].includes(a))continue;const label={deal:'Deal tiles','next-round':'Start next round',pass:'Pass'}[a];if(!label)continue;const b=make('button','',label);b.disabled=ctx.busy||ctx.session.status!=='active';b.onclick=()=>send(a);host.append(b);}return host;}
  function send(action,payload={}){selected=null;pendingDraw=false;closeDraw();void ctx.performAction(action,payload,action==='deal'?'dominos-deal':'');}
  function drawTargets(s,geometry){stage.querySelectorAll('.dm-target').forEach(n=>n.remove());if(!selected||ctx.busy||ctx.session.status!=='active')return;for(const m of s.legalMoves||[]){if(m.tile!==selected)continue;let q=geometry.ends[m.end];if(!q)continue;q={...q};const halves=selected.split('-');if(halves[0]===halves[1]&&m.end!=='start'){const horizontal=q.w>q.h,shift=(horizontal?q.w:q.h)/4*(q.reverse?-1:1);if(horizontal)q.x-=shift;else q.y-=shift;[q.w,q.h]=[q.h,q.w];}const b=make('button','dm-target');b.innerHTML=art(selected,q.w>q.h);b.setAttribute('aria-label','Play on '+m.end+' end');b.dataset.end=m.end;position(b,q);b.onclick=()=>send('play',m);stage.append(b);}}
  function select(t,s,g){selected=selected===t?null:t;stage.querySelectorAll('.dm-hand button').forEach(b=>{b.classList.toggle('is-selected',b.dataset.tile===selected);b.setAttribute('aria-pressed',String(b.dataset.tile===selected));});drawTargets(s,g);}
  function drag(b,t,s,g){let start=null,ghost=null;const clear=()=>{ghost?.remove();ghost=null;start=null;b.style.opacity='';stage.querySelectorAll('.dm-target').forEach(n=>n.classList.remove('is-over'));};let suppress=0;
    b.onclick=()=>{if(Date.now()>suppress)select(t,s,g);};
    b.onpointerdown=e=>{if(e.button!==0||b.disabled)return;start={x:e.clientX,y:e.clientY};b.setPointerCapture(e.pointerId);};
    b.onpointermove=e=>{if(!start)return;if(!ghost&&Math.hypot(e.clientX-start.x,e.clientY-start.y)<7)return;if(!ghost){selected=t;drawTargets(s,g);ghost=tile(t,'dm-ghost');const r=b.getBoundingClientRect();ghost.style.width=r.width+'px';ghost.style.height=r.height+'px';document.body.append(ghost);b.style.opacity='.25';}ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px';for(const n of stage.querySelectorAll('.dm-target')){const r=n.getBoundingClientRect();n.classList.toggle('is-over',e.clientX>=r.left-10&&e.clientX<=r.right+10&&e.clientY>=r.top-10&&e.clientY<=r.bottom+10);}};
    b.onpointerup=()=>{if(ghost){suppress=Date.now()+500;const target=stage.querySelector('.dm-target.is-over');const end=target?.dataset.end;clear();if(end)send('play',{tile:t,end});else{selected=null;select(t,s,g);select(t,s,g);}}else clear();};b.onpointercancel=b.onlostpointercapture=clear;
  }
  function closeDraw(){root?.querySelector('.dm-draw-dialog')?.remove();}
  function openDraw(s){if(pendingDraw||ctx.busy||ctx.session.status!=='active'||!s.legalActions?.includes('draw'))return;closeDraw();const dialog=make('dialog','dm-draw-dialog');const head=make('header');head.append(make('strong','','Draw a tile'));const x=make('button','','×');x.setAttribute('aria-label','Close draw pile');x.onclick=closeDraw;head.append(x);dialog.append(head,make('p','','Choose any face-down tile. Draw until you can play.'));const tiles=make('div','dm-stock-tiles');for(let i=0;i<s.stockCount;i++){const b=make('button','dm-back');b.setAttribute('aria-label','Draw face-down tile '+(i+1));b.onclick=()=>{pendingDraw=true;send('draw');};tiles.append(b);}dialog.append(tiles);dialog.onclick=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDraw();}};root.append(dialog);dialog.showModal();}
  function animateChange(s,old,sameSession,origin){
    if(!old||!sameSession||s.sequence===old.sequence)return;
    const last=s.lastAction||{},fx=ctx.optionCategory('visualFxEnabled',true),token=epoch;
    if(last.type==='deal'){sound(true);return;}
    if(last.type!=='play'&&last.type!=='draw')return;
    const mine=Number(last.userId)===Number(ctx.currentUserId());const selector=last.type==='play'?'.dm-board-tile':'.dm-hand button';
    const target=Array.from(stage.querySelectorAll(selector)).find(n=>n.dataset.tile===last.tile);
    if(!target){if(last.type==='draw'&&fx){const source=stage.querySelector('.dm-stock'),dest=stage.querySelector(`[data-player="${last.userId}"]`);if(source&&dest){const a=source.getBoundingClientRect(),b=dest.getBoundingClientRect(),scale=table.clientWidth/1100,r=stage.getBoundingClientRect(),back=make('div','dm-back dm-drawing');Object.assign(back.style,{left:(a.left+a.width/2-r.left)/scale+'px',top:(a.top+a.height/2-r.top)/scale+'px'});stage.append(back);animationUntil=performance.now()+950;back.animate([{transform:'translate(-50%,-50%)'},{transform:`translate(${(b.left+b.width/2-a.left-a.width/2)/scale-20}px,${(b.top+b.height/2-a.top-a.height/2)/scale-39}px)`}],{duration:900,easing:'ease-in-out'}).finished.finally(()=>back.remove());}}return;}
    if(!fx){if(last.type==='play')sound();return;}
    const source=last.type==='draw'?stage.querySelector('.dm-stock'):stage.querySelector(`[data-player="${last.userId}"]`);
    const a=target.getBoundingClientRect(),b=origin||source?.getBoundingClientRect()||a,scale=table.clientWidth/1100;
    let dx=(b.left+b.width/2-a.left-a.width/2)/scale,dy=(b.top+b.height/2-a.top-a.height/2)/scale;
    animationUntil=performance.now()+950;const motion=target.animate([{transform:`translate(${dx}px,${dy}px) scale(1.15)`},{transform:'translate(0,0) scale(1)'}],{duration:900,easing:'cubic-bezier(.2,.65,.2,1)'});
    motion.finished.then(()=>{if(token===epoch&&last.type==='play')sound();}).catch(()=>{});
  }
  function victory(s,old){if(!s.completed)return;const token=epoch;const show=()=>{if(token!==epoch||stage.querySelector('.dm-victory'))return;stage.querySelector('.dm-skip')?.remove();for(const id of s.winners||[])stage.querySelector(`[data-player="${id}"]`)?.classList.add('is-winner');const banner=make('div','dm-victory');const mine=(s.winners||[]).includes(Number(ctx.currentUserId()));banner.append(make('small','','MATCH COMPLETE'),make('strong','',mine?(s.settings?.tableMode==='teams'?'Your team wins!':'You win!'):'Match complete'),make('span','',(s.winners||[]).map(id=>ctx.memberName(id)).join(' + ')));banner.append(make('span','','Final score: '+Object.values(s.scores||{}).join(' / ')));const replay=make('button','','Replay celebration');replay.onclick=()=>{banner.remove();victory(s,{completed:false});};banner.append(replay);stage.append(banner);};if(old?.completed||!old||!ctx.optionCategory('visualFxEnabled',true)){show();return;}const skip=make('button','dm-skip','Skip celebration');skip.onclick=()=>{for(const n of stage.querySelectorAll('.dm-board-tile'))for(const a of n.getAnimations())a.finish();animationUntil=0;show();};stage.append(skip);animationUntil=performance.now()+2500;setTimeout(()=>{if(token!==epoch||stage.querySelector('.dm-victory'))return;stage.querySelectorAll('.dm-board-tile').forEach((n,i)=>n.animate([{boxShadow:'0 0 0 transparent'},{boxShadow:'0 0 24px 5px #ffda85',offset:.5},{boxShadow:'0 0 0 transparent'}],{duration:650,delay:i*30}));},900);setTimeout(show,2200);}
  function render(c){ctx=c;if(!root)setup();const s=c.session.state||{},sessionKey=c.session.publicId;const key=JSON.stringify([sessionKey,s.sequence,s.phase,c.session.status,c.options,c.session.members,c.busy]);
    if(c.options?.effectsEnabled===false)stopSound();if(key===lastKey){fit();return root;}
    if(previous?.sessionKey!==sessionKey){epoch++;selected=null;stopSound();previous=null;}
    if(performance.now()<animationUntil&&previous?.state.sequence===s.sequence){return root;}
    lastKey=key;const old=previous?.state;const changed=!old||s.sequence!==old.sequence;if(changed){epoch++;selected=null;closeDraw();}
    const playedSource=Array.from(stage.querySelectorAll('.dm-hand button')).find(n=>n.dataset.tile===s.lastAction?.tile);
    const origin=changed&&s.lastAction?.type==='play'&&Number(s.lastAction.userId)===Number(c.currentUserId())?playedSource?.getBoundingClientRect():null;
    stage.replaceChildren();const rail=make('div','dm-rail');rail.append(make('span','',s.settings?.tableMode==='teams'?'ALL FIVES · TEAMS':'ALL FIVES'),make('span','',`Round ${s.roundNumber||1} · To ${s.targetScore||200}`));stage.append(rail);
    const order=s.turnOrder?.length?s.turnOrder:(c.session.members||[]).filter(m=>['player','master'].includes(m.role)).map(m=>Number(m.userId));const viewer=Number(c.currentUserId()),start=Math.max(0,order.indexOf(viewer)),rotated=order.slice(start).concat(order.slice(0,start));
    const places=rotated.length===2?[[25,480],[875,45]]:[[25,480],[25,45],[875,45],[875,480]];
    rotated.forEach((id,i)=>{const member=(c.session.members||[]).find(m=>Number(m.userId)===id)||s.bots?.[id]||{userId:id};const p=make('div','dm-player');p.dataset.player=id;Object.assign(p.style,{left:places[i][0]+'px',top:places[i][1]+'px'});if(s.settings?.tableMode==='teams')p.classList.add(String(s.teams?.[id])==='0'?'team-violet':'team-gold');if(id===Number(c.session.turnUserId))p.classList.add('is-turn');const well=make('span','dm-avatar');well.append(c.memberAvatar(member,'dm-avatar-image'));p.append(well);const label=make('div');label.append(make('strong','',c.memberName(id)),make('small','',id===viewer?'You':s.settings?.tableMode==='teams'&&s.teams?.[id]===s.teams?.[viewer]?'Your partner':''),make('span','',`${s.handCounts?.[id]??0} tiles`));p.append(label);stage.append(p);});
    const score=make('aside','dm-score');score.append(make('strong','','SCORECARD'));for(const [group,n]of Object.entries(s.scores||{})){const row=make('div');const names=order.filter(id=>String(s.teams?.[id])===String(group)).map(id=>c.memberName(id));row.append(make('span','',names.join(' + ')),make('b','',n));score.append(row);}stage.append(score);
    const stock=make('button','dm-stock');stock.append(make('span','dm-stack','▰'),make('span','',`Draw pile · ${s.stockCount||0}`));stock.disabled=c.busy||c.session.status!=='active'||!s.legalActions?.includes('draw');stock.onclick=()=>openDraw(s);stage.append(stock);
    const turn=make('div','dm-turn',s.phase==='lobby'?'Waiting for players':s.completed?'Match complete':c.memberName(c.session.turnUserId)+' to play');stage.append(turn);
    const g=coords(s);for(const q of g.out){const t=q.near===undefined?q.tile:(q.reverse?`${q.far}-${q.near}`:`${q.near}-${q.far}`);const n=tile(t,'dm-board-tile'+(q.spinner?' dm-spinner':''),q.w>q.h);n.dataset.tile=q.tile;n.setAttribute('role','img');n.setAttribute('aria-label',q.tile.replace('-',' and ')+' domino'+(q.spinner?', spinner':''));position(n,q);stage.append(n);}
    const hand=make('div','dm-hand');for(const t of s.hand||[]){const b=make('button');b.dataset.tile=t;b.innerHTML=art(t);b.setAttribute('aria-label',t.replace('-',' and ')+' domino');b.setAttribute('aria-pressed',String(t===selected));b.classList.toggle('is-selected',t===selected);b.disabled=c.busy||!s.legalMoves?.some(m=>m.tile===t)||c.session.status!=='active';drag(b,t,s,g);hand.append(b);}if((s.hand||[]).length>9)hand.style.setProperty('--dm-hand-width',Math.max(20,510/s.hand.length-5)+'px');stage.append(hand);
    stage.append(make('div','dm-hand-label',s.hand?.length?'YOUR HAND':'') ,actions(s));drawTargets(s,g);
    if(s.lastRound&&!s.completed){const summary=make('div','dm-round');summary.append(make('strong','',s.lastRound.blocked?'Round blocked':'Round complete'));for(const [id,points]of Object.entries(s.lastRound.awards||{}))summary.append(make('span','',order.filter(u=>String(s.teams[u])===id).map(u=>c.memberName(u)).join(' + ')+` +${points}`));stage.append(summary);}
    fit();requestAnimationFrame(()=>{if(root.isConnected){fit();animateChange(s,old,Boolean(previous&&previous.sessionKey===sessionKey),origin);victory(s,old);}});previous={sessionKey,state:structuredClone(s)};return root;
  }
  window.addEventListener('pagehide',()=>{epoch++;stopSound();document.querySelectorAll('.dm-ghost').forEach(n=>n.remove());});
  window.CoreChatDominos={render,isAnimating:()=>performance.now()<animationUntil};
})();
